=== UO295679/sew/xml/etapa.dtd
<!ELEMENT etapa (nombre, numero, longitud, fecha, tiempoGanador, velocidadMedia, desnivel, tipo, salida, llegada, referencias, galeriaFotografias, galeriaVideos, galeriaSonidos, hitos, clasificacionEtapa, clasificacionGeneral, clasificacionEquipos)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT numero (#PCDATA)>

<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud
    unidad CDATA #REQUIRED
>

<!ELEMENT fecha (#PCDATA)>

<!ELEMENT tiempoGanador (#PCDATA)>

<!ELEMENT velocidadMedia (#PCDATA)>
<!ATTLIST velocidadMedia
    unidad CDATA #REQUIRED
>

<!ELEMENT desnivel (#PCDATA)>
<!ATTLIST desnivel
    unidad CDATA #REQUIRED
>

<!ELEMENT tipo (#PCDATA)>


<!-- SALIDA Y LLEGADA -->

<!ELEMENT salida (lugar, coordenadas)>

<!ELEMENT llegada (lugar, coordenadas)>

<!ELEMENT lugar (#PCDATA)>


<!-- COORDENADAS -->

<!ELEMENT coordenadas (longitudGeografica, latitud, altitud)>

<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud
    unidad CDATA #REQUIRED
>

<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud
    unidad CDATA #REQUIRED
>

<!ELEMENT longitudGeografica (#PCDATA)>
<!ATTLIST longitudGeografica
    unidad CDATA #REQUIRED
>

<!-- REFERENCIAS -->

<!ELEMENT referencias (referencia, referencia, referencia, referencia*)>

<!ELEMENT referencia (#PCDATA)>


<!-- FOTOGRAFÍAS -->

<!ELEMENT galeriaFotografias (fotografia+)>

<!ELEMENT fotografia (#PCDATA)>
<!ATTLIST fotografia
    archivo CDATA #REQUIRED
>


<!-- VÍDEOS -->

<!ELEMENT galeriaVideos (video+)>

<!ELEMENT video (#PCDATA)>
<!ATTLIST video
    archivo CDATA #REQUIRED
>


<!-- SONIDOS -->

<!ELEMENT galeriaSonidos (sonido+)>

<!ELEMENT sonido (#PCDATA)>
<!ATTLIST sonido
    archivo CDATA #REQUIRED
>


<!-- HITOS -->

<!ELEMENT hitos (puertoMontana*, sprintIntermedio*, sprintBonificado*, puntoAnonimo*)>

<!ELEMENT puertoMontana (nombre, coordenadas, distanciaDesdeSalida)>

<!ATTLIST puertoMontana
    categoria (especial | primera | segunda | tercera | bonificado) #REQUIRED
>

<!ELEMENT sprintIntermedio (nombre, coordenadas, distanciaDesdeSalida)>

<!ELEMENT sprintBonificado (nombre, coordenadas, distanciaDesdeSalida)>

<!ELEMENT puntoAnonimo (nombre?, coordenadas, distanciaDesdeSalida)>


<!-- DISTANCIA -->

<!ELEMENT distanciaDesdeSalida (#PCDATA)>

<!ATTLIST distanciaDesdeSalida
    unidad CDATA #REQUIRED
>


<!-- CLASIFICACIÓN DE LA ETAPA -->

<!ELEMENT clasificacionEtapa (corredor, corredor, corredor)>

<!ELEMENT corredor (nombre, equipoCorredor, tiempo, diferencia)>

<!ELEMENT equipoCorredor (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT diferencia (#PCDATA)>

<!ATTLIST corredor
    posicion (1 | 2 | 3) #REQUIRED
>


<!-- CLASIFICACIÓN GENERAL -->

<!ELEMENT clasificacionGeneral (corredor, corredor, corredor)>


<!-- CLASIFICACIÓN POR EQUIPOS -->

<!ELEMENT clasificacionEquipos (equipo, equipo, equipo)>

<!ELEMENT equipo (nombre, tiempo, diferencia)>

<!ATTLIST equipo
    posicion (1 | 2 | 3) #REQUIRED
>

=== UO295679/sew/xml/etapa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etapa SYSTEM "etapa.dtd">

<etapa>
    <nombre>Carrefour Granada a Granada</nombre>
    <numero>21</numero>

    <longitud unidad="km">112</longitud>

    <fecha>2026-09-13</fecha>

    <tiempoGanador>02:54:08</tiempoGanador>

    <velocidadMedia unidad="km/h">31.87</velocidadMedia>

    <desnivel unidad="m">1217</desnivel>

    <tipo>llana</tipo>

    <salida>
        <lugar>Carrefour Granada</lugar>
        <coordenadas>
            <longitudGeografica unidad="grados">-3.60759</longitudGeografica>
            <latitud unidad="grados">37.15443</latitud>
            <altitud unidad="m">680</altitud>
        </coordenadas>
    </salida>

    <llegada>
        <lugar>Granada</lugar>
        <coordenadas>
            <longitudGeografica unidad="grados">-3.5947512</longitudGeografica>
            <latitud unidad="grados">37.1697044</latitud>
            <altitud unidad="m">675</altitud>
        </coordenadas>
    </llegada>

    <referencias>
        <referencia>https://www.carrefour.es/tiendas-carrefour/andalucia/granada/</referencia>
        <referencia>https://turgranada.es/</referencia>
        <referencia>https://www.granada.org/</referencia>
    </referencias>

    <galeriaFotografias>
        <fotografia archivo="multimedia/foto1.jpg">
            Fotografía de la etapa
        </fotografia>
    </galeriaFotografias>

    <galeriaVideos>
        <video archivo="multimedia/video1.mp4">
            Vídeo de la etapa
        </video>
    </galeriaVideos>

    <galeriaSonidos>
        <sonido archivo="multimedia/sonido1.mp3">
            Podcast de la etapa
        </sonido>
    </galeriaSonidos>

    <hitos>
        <sprintIntermedio>
            <nombre>Sprint intermedio</nombre>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.591533</longitudGeografica>
                <latitud unidad="grados">37.170686</latitud>
                <altitud unidad="m">675</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">92.4</distanciaDesdeSalida>
        </sprintIntermedio>
        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6120</longitudGeografica>
                <latitud unidad="grados">37.1480</latitud>
                <altitud unidad="m">670</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">4.5</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6210</longitudGeografica>
                <latitud unidad="grados">37.1390</latitud>
                <altitud unidad="m">650</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">9.0</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6350</longitudGeografica>
                <latitud unidad="grados">37.1420</latitud>
                <altitud unidad="m">645</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">13.5</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6450</longitudGeografica>
                <latitud unidad="grados">37.1510</latitud>
                <altitud unidad="m">640</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">18.0</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6620</longitudGeografica>
                <latitud unidad="grados">37.1580</latitud>
                <altitud unidad="m">630</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">22.5</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6780</longitudGeografica>
                <latitud unidad="grados">37.1650</latitud>
                <altitud unidad="m">625</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">27.0</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6980</longitudGeografica>
                <latitud unidad="grados">37.1750</latitud>
                <altitud unidad="m">600</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">31.5</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.7180</longitudGeografica>
                <latitud unidad="grados">37.1890</latitud>
                <altitud unidad="m">582</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">36.0</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.7500</longitudGeografica>
                <latitud unidad="grados">37.1920</latitud>
                <altitud unidad="m">570</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">40.5</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.7750</longitudGeografica>
                <latitud unidad="grados">37.1980</latitud>
                <altitud unidad="m">560</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">45.0</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.7920</longitudGeografica>
                <latitud unidad="grados">37.2150</latitud>
                <altitud unidad="m">555</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">49.5</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.7650</longitudGeografica>
                <latitud unidad="grados">37.2250</latitud>
                <altitud unidad="m">562</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">54.0</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.7420</longitudGeografica>
                <latitud unidad="grados">37.2360</latitud>
                <altitud unidad="m">570</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">58.5</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.7150</longitudGeografica>
                <latitud unidad="grados">37.2320</latitud>
                <altitud unidad="m">585</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">63.0</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6910</longitudGeografica>
                <latitud unidad="grados">37.2280</latitud>
                <altitud unidad="m">600</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">67.5</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6700</longitudGeografica>
                <latitud unidad="grados">37.2220</latitud>
                <altitud unidad="m">608</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">72.0</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6540</longitudGeografica>
                <latitud unidad="grados">37.2180</latitud>
                <altitud unidad="m">615</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">76.5</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6300</longitudGeografica>
                <latitud unidad="grados">37.2050</latitud>
                <altitud unidad="m">630</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">81.0</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.6010</longitudGeografica>
                <latitud unidad="grados">37.1950</latitud>
                <altitud unidad="m">650</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">85.5</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.5840</longitudGeografica>
                <latitud unidad="grados">37.1820</latitud>
                <altitud unidad="m">670</altitud>
            </coordenadas>
            <distanciaDesdeSalida unidad="km">94.0</distanciaDesdeSalida>
        </puntoAnonimo>

        <puntoAnonimo>
            <coordenadas>
                <longitudGeografica unidad="grados">-3.5840</longitudGeografica>
                <latitud unidad="grados">37.1200</latitud>
                <altitud unidad="m">770</altitud>
            </coordenadas>
